import { supabase } from '../../config/supabase';
import type { CapaAction, NcrAttachment, NcrRecord, NcrStatus, NcrVerification } from '../../types/ncr';
import { getUserNameByEmail } from '../../utils/ncr/userUtils';

export interface CreateNcrPayload {
    date: string;
    shift?: 'A' | 'B' | 'C';
    department: string;
    title?: string;
    defectId?: string;
    defectType?: 'raw_material' | 'product' | 'process' | 'other';
    occurrence?: number;
    detection?: number;
    rpn?: number;
    riskBand?: string;
    productName?: string;
    lineOrArea?: string;
    reservedQty?: string;
    reservedUnit?: string;
    severity: 'low' | 'medium' | 'high';
    standardDefect?: string;
    customType?: string;
    discoveredBy: string;
    createdBy: string;
    description: string;
    immediateAction?: string;
    attachments?: File[];
    // Integration links - حقول الربط
    relatedLabTestId?: string;
    relatedLabTestNumber?: string;
    relatedMaterialReceivingId?: string;
    relatedMaterialName?: string;
    relatedBatchNumber?: string;
    relatedSupplierId?: string;
    relatedSupplierName?: string;
    autoGeneratedFromLab?: boolean;
    companyId?: string;
}

export interface UpdateNcrPayload extends Partial<CreateNcrPayload> {
    id: string;
    status?: NcrStatus;
    rootCause?: string;
    closedAt?: string | null;
    actions?: CapaAction[];
    holds?: NcrRecord['holds'];
    verification?: NcrVerification;
}

const NCR_TABLE = 'ncr_reports';
const META_TABLE = 'meta';
const NCR_SELECT_COLUMNS = 'id, number, title, date, shift, department, product_name, line_or_area, reserved_qty, reserved_unit, severity, defect_id, defect_type, occurrence, detection, rpn, risk_band, standard_defect, custom_type, discovered_by, created_by, description, immediate_action, root_cause, actions, holds, verification, attachments, created_at, updated_at, closed_at, current_stage, completed_stages, stage_history, root_cause_approval, status, related_lab_test_id, related_lab_test_number, related_material_receiving_id, related_material_name, related_batch_number, related_supplier_id, related_supplier_name, auto_generated_from_lab, company_id';

function formatDate(date: string): { year: number } {
    const d = new Date(date);
    return { year: d.getFullYear() };
}

export async function generateNextNcrNumber(targetDate: string, maxRetries = 3): Promise<string> {
    const { year } = formatDate(targetDate);
    const counterKey = `ncr_counter_${year}`;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            // Try atomic increment using RPC or direct SQL
            // First, try to get and increment atomically using upsert with conflict handling
            const { data: existingData } = await supabase
                .from(META_TABLE)
                .select('id, sequences')
                .eq('id', 'ncrCounters')
                .single();

            let sequences: Record<string, number> = existingData?.sequences || {};
            const currentValue = sequences[year] ?? 0;
            const nextValue = currentValue + 1;
            sequences[year] = nextValue;

            // Use upsert with optimistic locking pattern
            const { error: upsertError } = await supabase
                .from(META_TABLE)
                .upsert({
                    id: 'ncrCounters',
                    sequences,
                    updated_at: new Date().toISOString()
                }, {
                    onConflict: 'id'
                });

            if (upsertError) {
                // If conflict or error on last attempt, throw
                if (attempt === maxRetries) {
                    throw upsertError;
                }
                // Otherwise wait a bit and retry
                await new Promise(resolve => setTimeout(resolve, 50 * attempt));
                continue;
            }

            // Verify we got a unique number by checking if it was already used
            const paddedNumber = String(nextValue).padStart(4, '0');
            const ncrNumber = `NCR-${year}-${paddedNumber}`;

            const { data: existingNcr } = await supabase
                .from(NCR_TABLE)
                .select('id')
                .eq('number', ncrNumber)
                .single();

            if (existingNcr) {
                // Number already exists, retry
                if (attempt === maxRetries) {
                    throw new Error(`NCR number ${ncrNumber} already exists after ${maxRetries} attempts`);
                }
                continue;
            }

            return ncrNumber;

        } catch (err) {
            const errorMessage = (err as any)?.message || '';
            const errorCode = (err as any)?.code || '';
            // If meta table missing or RLS prevents insert, fall back immediately to timestamp-based number
            if (
                errorCode === 'PGRST205' ||
                errorMessage.includes("Could not find the table 'public.meta'") ||
                errorCode === '42501'
            ) {
                const fallbackNumber = `NCR-${year}-${Date.now().toString().slice(-6)}`;
                console.warn(`[NCR] META unavailable (code ${errorCode}), using fallback number ${fallbackNumber}`);
                return fallbackNumber;
            }
            if (attempt === maxRetries) {
                console.error('Failed to generate NCR number after retries:', err);
                throw err;
            }
            // Wait and retry
            await new Promise(resolve => setTimeout(resolve, 100 * attempt));
        }
    }

    // Fallback: generate with timestamp suffix for uniqueness
    const fallbackNumber = `NCR-${year}-${Date.now().toString().slice(-6)}`;
    console.warn(`Using fallback NCR number: ${fallbackNumber}`);
    return fallbackNumber;
}

async function uploadAttachments(ncrId: string, files: File[] = []): Promise<NcrAttachment[]> {
    if (!files.length) return [];

    const uploads = files.map(async (file) => {
        const path = `attachments/${ncrId}/${Date.now()}-${file.name}`;

        const { error: uploadError } = await supabase.storage
            .from('ncr-attachments')
            .upload(path, file);

        if (uploadError) {
            console.error('Upload error:', uploadError);
            throw uploadError;
        }

        const { data: urlData } = supabase.storage
            .from('ncr-attachments')
            .getPublicUrl(path);

        const attachment: NcrAttachment = {
            id: crypto.randomUUID(),
            fileName: file.name,
            storagePath: path,
            downloadURL: urlData.publicUrl,
            uploadedAt: new Date().toISOString()
        };

        return attachment;
    });

    return Promise.all(uploads);
}

export async function createNcr(payload: CreateNcrPayload): Promise<NcrRecord> {
    const companyId = payload.companyId?.trim();
    if (!companyId) {
        throw new Error('يجب اختيار الشركة قبل إنشاء تقرير عدم المطابقة');
    }

    const ncrNumber = await generateNextNcrNumber(payload.date);
    const ncrId = crypto.randomUUID();
    const now = new Date().toISOString();

    const attachments = await uploadAttachments(ncrId, payload.attachments ?? []);

    // Ensure createdBy and discoveredBy are never undefined
    const createdByValue = payload.createdBy || 'مستخدم غير معرف';
    const discoveredByValue = payload.discoveredBy || 'مستخدم غير معرف';

    const resolvedDiscoveredBy = discoveredByValue.includes('@')
        ? (await getUserNameByEmail(discoveredByValue)) || discoveredByValue
        : discoveredByValue;
    const resolvedCreatedBy = createdByValue.includes('@')
        ? (await getUserNameByEmail(createdByValue)) || createdByValue
        : createdByValue;

    const ncrData = {
        id: ncrId,
        number: ncrNumber,
        date: payload.date,
        shift: payload.shift ?? null,
        department: payload.department,
        title: payload.title || payload.description?.slice(0, 120) || 'NCR',
        product_name: payload.productName ?? null,
        line_or_area: payload.lineOrArea ?? null,
        reserved_qty: payload.reservedQty ?? null,
        reserved_unit: payload.reservedUnit ?? null,
        severity: payload.severity,
        defect_id: payload.defectId || null,
        defect_type: payload.defectType ?? null,
        occurrence: payload.occurrence ?? null,
        detection: payload.detection ?? null,
        rpn: payload.rpn ?? null,
        risk_band: payload.riskBand ?? null,
        standard_defect: payload.standardDefect ?? null,
        custom_type: payload.customType ?? null,
        discovered_by: resolvedDiscoveredBy,
        created_by: resolvedCreatedBy,
        description: payload.description,
        immediate_action: payload.immediateAction ?? null,
        root_cause: null,
        actions: [],
        holds: [],
        verification: null,
        attachments,
        created_at: now,
        updated_at: now,
        closed_at: null,
        current_stage: 'initial_report',
        completed_stages: [],
        stage_history: [{
            from: null,
            to: 'initial_report',
            transitionedBy: resolvedCreatedBy,
            transitionedByName: resolvedCreatedBy,
            transitionedByEmail: createdByValue,
            transitionedAt: now,
            notes: payload.autoGeneratedFromLab ? 'تم إنشاء التقرير تلقائياً من المختبر' : 'تم إنشاء التقرير'
        }],
        root_cause_approval: null,
        status: 'open',
        // Integration links
        related_lab_test_id: payload.relatedLabTestId ?? null,
        related_lab_test_number: payload.relatedLabTestNumber ?? null,
        related_material_receiving_id: payload.relatedMaterialReceivingId ?? null,
        related_material_name: payload.relatedMaterialName ?? null,
        related_batch_number: payload.relatedBatchNumber ?? null,
        related_supplier_id: payload.relatedSupplierId ?? null,
        related_supplier_name: payload.relatedSupplierName ?? null,
        auto_generated_from_lab: payload.autoGeneratedFromLab ?? false,
        company_id: companyId
    };

    const { error } = await supabase.from(NCR_TABLE).insert(ncrData);
    if (error) throw error;

    return (await getNcrById(ncrId, companyId))!;
}

export async function getNcrById(id: string, companyId?: string | null): Promise<NcrRecord | null> {
    let query = supabase
        .from(NCR_TABLE)
        .select(NCR_SELECT_COLUMNS)
        .eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { data, error } = await query.single();

    if (error || !data) return null;
    return normalizeNcr(data);
}

export async function fetchNcrs(companyId?: string | null): Promise<NcrRecord[]> {
    let query = supabase
        .from(NCR_TABLE)
        .select(NCR_SELECT_COLUMNS)
        .order('created_at', { ascending: false })
        .limit(200);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { data, error } = await query;

    if (error) throw error;
    return (data || []).map(normalizeNcr);
}

export async function updateNcr(payload: UpdateNcrPayload) {
    const updates: Record<string, unknown> = {
        updated_at: new Date().toISOString()
    };

    if (payload.date) updates.date = payload.date;
    if (payload.shift !== undefined) updates.shift = payload.shift;
    if (payload.department) updates.department = payload.department;
    if (payload.productName !== undefined) updates.product_name = payload.productName;
    if (payload.lineOrArea !== undefined) updates.line_or_area = payload.lineOrArea;
    if (payload.reservedQty !== undefined) updates.reserved_qty = payload.reservedQty;
    if (payload.reservedUnit !== undefined) updates.reserved_unit = payload.reservedUnit;
    if (payload.severity) updates.severity = payload.severity;
    if (payload.defectId !== undefined) updates.defect_id = payload.defectId;
    if (payload.defectType !== undefined) updates.defect_type = payload.defectType;
    if (payload.occurrence !== undefined) updates.occurrence = payload.occurrence;
    if (payload.detection !== undefined) updates.detection = payload.detection;
    if (payload.rpn !== undefined) updates.rpn = payload.rpn;
    if (payload.riskBand !== undefined) updates.risk_band = payload.riskBand;
    if (payload.standardDefect !== undefined) updates.standard_defect = payload.standardDefect;
    if (payload.customType !== undefined) updates.custom_type = payload.customType;
    if (payload.discoveredBy) {
        if (payload.discoveredBy.includes('@')) {
            const n = await getUserNameByEmail(payload.discoveredBy);
            updates.discovered_by = n || payload.discoveredBy;
        } else {
            updates.discovered_by = payload.discoveredBy;
        }
    }
    if (payload.createdBy) {
        if (payload.createdBy.includes('@')) {
            const n = await getUserNameByEmail(payload.createdBy);
            updates.created_by = n || payload.createdBy;
        } else {
            updates.created_by = payload.createdBy;
        }
    }
    if (payload.description) updates.description = payload.description;
    if (payload.immediateAction !== undefined) updates.immediate_action = payload.immediateAction;
    if (payload.status) updates.status = payload.status;
    if (payload.rootCause !== undefined) updates.root_cause = payload.rootCause;
    if (payload.closedAt !== undefined) updates.closed_at = payload.closedAt;
    if (payload.actions) updates.actions = payload.actions;
    if (payload.holds !== undefined) updates.holds = payload.holds;
    if (payload.verification !== undefined) updates.verification = payload.verification;

    let query = supabase.from(NCR_TABLE).update(updates).eq('id', payload.id);
    if (payload.companyId) {
        query = query.eq('company_id', payload.companyId);
    }
    const { error } = await query;
    if (error) throw error;
    return (await getNcrById(payload.id, payload.companyId))!;
}

export async function appendAttachments(id: string, files: File[], companyId?: string | null) {
    if (!files.length) return await getNcrById(id, companyId);
    const ncr = await getNcrById(id, companyId);
    if (!ncr) throw new Error('NCR not found');
    const newAttachments = await uploadAttachments(id, files);

    let query = supabase.from(NCR_TABLE).update({
        attachments: [...ncr.attachments, ...newAttachments],
        updated_at: new Date().toISOString()
    }).eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { error } = await query;
    if (error) throw error;

    return (await getNcrById(id, companyId))!;
}

export async function deleteNcr(id: string, companyId?: string | null) {
    let query = supabase.from(NCR_TABLE).delete().eq('id', id);
    if (companyId) {
        query = query.eq('company_id', companyId);
    }
    const { error } = await query;
    if (error) throw error;
}

function normalizeNcr(data: Record<string, unknown>): NcrRecord {
    const attachments: NcrAttachment[] = Array.isArray(data.attachments)
        ? data.attachments
        : [];

    const actions: CapaAction[] = Array.isArray(data.actions) ? data.actions : [];
    const holds = Array.isArray(data.holds) ? data.holds : [];

    return {
        id: data.id as string,
        number: data.number as string,
        date: data.date as string || new Date().toISOString().split('T')[0],
        department: data.department as string,
        title: (data.title as string) ?? undefined,
        productName: (data.product_name as string) ?? undefined,
        reservedQty: (data.reserved_qty as string) ?? undefined,
        reservedUnit: (data.reserved_unit as string) ?? undefined,
        severity: data.severity as NcrRecord['severity'],
        defectId: (data.defect_id as string) ?? undefined,
        defectType: (data.defect_type as string) as NcrRecord['defectType'] | undefined,
        occurrence: (data.occurrence as number) ?? undefined,
        detection: (data.detection as number) ?? undefined,
        rpn: (data.rpn as number) ?? undefined,
        riskBand: (data.risk_band as string) ?? undefined,
        lineOrArea: (data.line_or_area as string) ?? undefined,
        standardDefect: (data.standard_defect as string) ?? undefined,
        customType: (data.custom_type as string) ?? undefined,
        discoveredBy: data.discovered_by as string,
        createdBy: data.created_by as string,
        description: data.description as string,
        immediateAction: (data.immediate_action as string) ?? undefined,
        status: (data.status as NcrRecord['status']) ?? 'open',
        rootCause: (data.root_cause as string) ?? undefined,
        actions,
        holds,
        verification: (data.verification as NcrVerification) ?? undefined,
        attachments,
        shift: (data.shift as NcrRecord['shift']) ?? undefined,
        createdAt: data.created_at as string || new Date().toISOString(),
        updatedAt: data.updated_at as string || new Date().toISOString(),
        closedAt: data.closed_at ? (data.closed_at as string) : undefined,
        currentStage: (data.current_stage as NcrRecord['currentStage']) || 'initial_report',
        completedStages: Array.isArray(data.completed_stages) ? data.completed_stages : [],
        stageHistory: Array.isArray(data.stage_history) ? data.stage_history : [],
        rootCauseApproval: (data.root_cause_approval as NcrRecord['rootCauseApproval']) ?? undefined,
        // Integration links
        relatedLabTestId: (data.related_lab_test_id as string) ?? undefined,
        relatedLabTestNumber: (data.related_lab_test_number as string) ?? undefined,
        relatedMaterialReceivingId: (data.related_material_receiving_id as string) ?? undefined,
        relatedMaterialName: (data.related_material_name as string) ?? undefined,
        relatedBatchNumber: (data.related_batch_number as string) ?? undefined,
        relatedSupplierId: (data.related_supplier_id as string) ?? undefined,
        relatedSupplierName: (data.related_supplier_name as string) ?? undefined,
        autoGeneratedFromLab: (data.auto_generated_from_lab as boolean) ?? false,
        companyId: (data.company_id as string) ?? undefined
    };
}

// ============ Workflow Functions ============

/**
 * Propose root cause analysis
 */
export async function proposeRootCause(
    id: string,
    rootCauseText: string,
    proposedBy: string,
    proposedByName: string,
    proposedByEmail: string,
    proposedByRole: 'department' | 'quality',
    companyId?: string | null
): Promise<NcrRecord> {
    const now = new Date().toISOString();

    const rootCauseApproval = {
        proposedBy,
        proposedByName,
        proposedByEmail,
        proposedByRole,
        proposedAt: now,
        rootCauseText,
        status: 'pending' as const
    };

    let query = supabase.from(NCR_TABLE).update({
        root_cause: rootCauseText,
        root_cause_approval: rootCauseApproval,
        updated_at: now
    }).eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { error } = await query;
    if (error) throw error;

    return (await getNcrById(id, companyId))!;
}

/**
 * Approve or reject root cause analysis
 */
export async function reviewRootCause(
    id: string,
    approved: boolean,
    reviewedBy: string,
    reviewedByName: string,
    reviewedByEmail: string,
    reviewedByRole: 'department' | 'quality',
    rejectionReason?: string,
    companyId?: string | null
): Promise<NcrRecord> {
    const ncr = await getNcrById(id, companyId);
    if (!ncr || !ncr.rootCauseApproval) throw new Error('NCR or root cause approval not found');

    const now = new Date().toISOString();

    const updatedApproval = {
        ...ncr.rootCauseApproval,
        status: approved ? 'approved' : 'rejected',
        reviewedBy,
        reviewedByName,
        reviewedByEmail,
        reviewedByRole,
        reviewedAt: now,
        ...((!approved && rejectionReason) ? { rejectionReason } : {})
    };

    const updates: Record<string, unknown> = {
        root_cause_approval: updatedApproval,
        updated_at: now
    };

    // If approved, progress to next stage
    if (approved && ncr.currentStage === 'root_cause_analysis') {
        updates.current_stage = 'capa_planning';
        updates.completed_stages = [...(ncr.completedStages || []), 'root_cause_analysis'];
    }

    let query = supabase.from(NCR_TABLE).update(updates).eq('id', id);
    if (companyId) {
        query = query.eq('company_id', companyId);
    }
    const { error } = await query;
    if (error) throw error;
    return (await getNcrById(id, companyId))!;
}

/**
 * Add CAPA action
 */
export async function addCapaAction(
    id: string,
    action: {
        type: 'corrective' | 'preventive';
        description: string;
        responsibleDept: string;
        responsiblePerson: string;
        targetDate: string;
    },
    companyId?: string | null
): Promise<NcrRecord> {
    const ncr = await getNcrById(id, companyId);
    if (!ncr) throw new Error('NCR not found');

    const now = new Date().toISOString();

    const newAction = {
        id: crypto.randomUUID(),
        ...action,
        status: 'pending' as const
    };

    let query = supabase.from(NCR_TABLE).update({
        actions: [...(ncr.actions || []), newAction],
        updated_at: now
    }).eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { error } = await query;
    if (error) throw error;

    return (await getNcrById(id, companyId))!;
}

/**
 * Update CAPA action status
 */
export async function updateCapaStatus(
    id: string,
    actionId: string,
    status: 'pending' | 'in-progress' | 'completed',
    companyId?: string | null
): Promise<NcrRecord> {
    const ncr = await getNcrById(id, companyId);
    if (!ncr) throw new Error('NCR not found');

    const now = new Date().toISOString();

    const updatedActions = ncr.actions.map(a =>
        a.id === actionId ? { ...a, status } : a
    );

    let query = supabase.from(NCR_TABLE).update({
        actions: updatedActions,
        updated_at: now
    }).eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { error } = await query;
    if (error) throw error;

    return (await getNcrById(id, companyId))!;
}

/**
 * Progress to next workflow stage with state machine validation
 */
export async function progressToNextStage(
    id: string,
    transitionedBy: string,
    transitionedByName: string,
    transitionedByEmail: string,
    notes?: string,
    companyId?: string | null
): Promise<NcrRecord> {
    const ncr = await getNcrById(id, companyId);
    if (!ncr) throw new Error('NCR not found');

    // Import state machine for validation
    const { validateTransition, getNextStage, NCR_STAGE_LABELS } = await import('../../utils/ncr/ncrStateMachine');

    // Validate transition using state machine
    const validation = validateTransition({
        currentStage: ncr.currentStage as any,
        description: ncr.description,
        department: ncr.department,
        severity: ncr.severity,
        rootCauseApproval: ncr.rootCauseApproval,
        actions: ncr.actions
    });

    if (!validation.isValid) {
        throw new Error(validation.blockedReason_ar || validation.blockedReason || 'Cannot progress to next stage');
    }

    const nextStage = validation.to;
    if (!nextStage) {
        throw new Error('لا يمكن التقدم أكثر - المرحلة النهائية');
    }

    const now = new Date().toISOString();

    const newTransition = {
        from: ncr.currentStage,
        to: nextStage,
        transitionedBy,
        transitionedByName,
        transitionedByEmail,
        transitionedAt: now,
        notes: notes || ''
    };

    let query = supabase.from(NCR_TABLE).update({
        current_stage: nextStage,
        completed_stages: [...(ncr.completedStages || []), ncr.currentStage],
        stage_history: [...(ncr.stageHistory || []), newTransition],
        updated_at: now
    }).eq('id', id);

    if (companyId) {
        query = query.eq('company_id', companyId);
    }

    const { error } = await query;
    if (error) throw error;

    return (await getNcrById(id, companyId))!;
}

/**
 * Verify and close NCR
 */
export async function verifyAndClose(
    id: string,
    verifiedBy: string,
    verificationNotes: string,
    result: 'success' | 'fail',
    companyId?: string | null
): Promise<NcrRecord> {
    const ncr = await getNcrById(id, companyId);
    if (!ncr) throw new Error('NCR not found');

    const now = new Date().toISOString();

    const verification = {
        verifiedBy,
        date: now,
        notes: verificationNotes,
        result
    };

    const updates: Record<string, unknown> = {
        verification,
        updated_at: now
    };

    if (result === 'success') {
        updates.status = 'closed';
        updates.closed_at = now;
        updates.current_stage = 'verification_closure';
        updates.completed_stages = [...(ncr.completedStages || []), 'verification_closure'];
    }

    let query = supabase.from(NCR_TABLE).update(updates).eq('id', id);
    if (companyId) {
        query = query.eq('company_id', companyId);
    }
    const { error } = await query;
    if (error) throw error;
    return (await getNcrById(id, companyId))!;
}
