/**
 * Integration Service - خدمة التكامل
 * ربط الوحدات المختلفة ببعضها البعض
 */

import type { LabTest, MaterialReceiving } from '../domain/lab/types';
import type { NcrRecord } from '../types/ncr';
import { createNcr, type CreateNcrPayload } from './ncr/ncrService';

// ============ Types ============

export interface AutoNcrFromLabResult {
    success: boolean;
    ncrId?: string;
    ncrNumber?: string;
    error?: string;
}

export interface SupplierQualityStats {
    supplierId: string;
    supplierName: string;
    totalReceivings: number;
    acceptedReceivings: number;
    rejectedReceivings: number;
    totalLabTests: number;
    passedLabTests: number;
    failedLabTests: number;
    totalNcrs: number;
    openNcrs: number;
    closedNcrs: number;
    qualityScore: number;  // 0-100
    isRecommendedForApproval: boolean;
}

// ============ Auto NCR from Lab ============

/**
 * Create an NCR automatically when a lab test is rejected
 * إنشاء تقرير عدم مطابقة تلقائياً عند رفض فحص معملي
 */
export async function createNcrFromRejectedLabTest(
    test: LabTest,
    material: MaterialReceiving | undefined,
    rejectionNotes: string,
    _userId: string,  // Reserved for future audit logs
    userName: string,
    companyId?: string
): Promise<AutoNcrFromLabResult> {
    try {
        const resolvedCompanyId = companyId || material?.companyId;
        if (!resolvedCompanyId) {
            return {
                success: false,
                error: 'Company context is required to create NCR'
            };
        }

        // Build description from lab test details
        const failedParams = test.parameters
            .filter(p => p.status === 'fail')
            .map(p => `${p.name}: ${p.result} (المواصفة: ${p.specification})`)
            .join('\\n');

        const description = `
**رفض فحص معملي تلقائي**

**رقم الفحص:** ${test.testNumber}
**نوع الفحص:** ${test.testType}
**اسم العينة:** ${test.sample.sourceName}

**المعايير المرفوضة:**
${failedParams}

**ملاحظات الرفض:**
${rejectionNotes || 'لا توجد ملاحظات'}
`.trim();

        // Prepare NCR payload
        const payload: CreateNcrPayload & {
            relatedLabTestId?: string;
            relatedLabTestNumber?: string;
            relatedMaterialReceivingId?: string;
            relatedMaterialName?: string;
            relatedBatchNumber?: string;
            relatedSupplierId?: string;
            relatedSupplierName?: string;
            autoGeneratedFromLab?: boolean;
        } = {
            date: new Date().toISOString().split('T')[0],
            department: 'المختبر',
            productName: test.sample.sourceName,
            severity: test.priority === 'critical' ? 'high' : test.priority === 'urgent' ? 'medium' : 'low',
            customType: 'فحص معملي مرفوض',
            discoveredBy: userName,
            createdBy: userName,
            description,
            immediateAction: 'تم حجز المادة بانتظار قرار الجودة',
            companyId: resolvedCompanyId,
            // Integration links
            relatedLabTestId: test.id,
            relatedLabTestNumber: test.testNumber,
            autoGeneratedFromLab: true
        };

        // Add material info if available
        if (material) {
            payload.relatedMaterialReceivingId = material.id;
            payload.relatedMaterialName = material.materialName;
            payload.relatedBatchNumber = material.batchNumber;
            payload.relatedSupplierId = material.supplierId;
            payload.relatedSupplierName = material.supplierName;
            payload.lineOrArea = material.storageLocation;
        }

        // Create the NCR
        const ncr = await createNcr(payload as CreateNcrPayload);

        return {
            success: true,
            ncrId: ncr.id,
            ncrNumber: ncr.number
        };
    } catch (error) {
        console.error('Failed to create NCR from rejected lab test:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error'
        };
    }
}

// ============ Supplier Quality Analytics ============

/**
 * Calculate supplier quality statistics
 * حساب إحصائيات جودة المورد
 */
export function calculateSupplierQualityStats(
    supplierId: string,
    supplierName: string,
    materials: MaterialReceiving[],
    labTests: LabTest[],
    ncrs: NcrRecord[]
): SupplierQualityStats {
    // Filter by supplier
    const supplierMaterials = materials.filter(m => m.supplierId === supplierId);
    const supplierLabTests = labTests.filter(t => {
        const material = materials.find(m => m.id === t.sample.sourceId);
        return material?.supplierId === supplierId;
    });
    const supplierNcrs = ncrs.filter(n => n.relatedSupplierId === supplierId);

    // Calculate counts
    const acceptedReceivings = supplierMaterials.filter(m => m.status === 'accepted').length;
    const rejectedReceivings = supplierMaterials.filter(m => m.status === 'rejected').length;
    const passedLabTests = supplierLabTests.filter(t => t.status === 'approved').length;
    const failedLabTests = supplierLabTests.filter(t => t.status === 'rejected').length;
    const openNcrs = supplierNcrs.filter(n => n.status !== 'closed').length;
    const closedNcrs = supplierNcrs.filter(n => n.status === 'closed').length;

    // Calculate quality score (0-100)
    let score = 100;

    // Receiving acceptance rate (40% weight)
    if (supplierMaterials.length > 0) {
        const acceptanceRate = acceptedReceivings / supplierMaterials.length;
        score -= (1 - acceptanceRate) * 40;
    }

    // Lab test pass rate (40% weight)
    if (supplierLabTests.length > 0) {
        const passRate = passedLabTests / supplierLabTests.length;
        score -= (1 - passRate) * 40;
    }

    // NCR penalty (-5 per open NCR, -2 per closed NCR)
    score -= openNcrs * 5;
    score -= closedNcrs * 2;

    // Ensure score is between 0 and 100
    score = Math.max(0, Math.min(100, Math.round(score)));

    return {
        supplierId,
        supplierName,
        totalReceivings: supplierMaterials.length,
        acceptedReceivings,
        rejectedReceivings,
        totalLabTests: supplierLabTests.length,
        passedLabTests,
        failedLabTests,
        totalNcrs: supplierNcrs.length,
        openNcrs,
        closedNcrs,
        qualityScore: score,
        isRecommendedForApproval: score >= 70 && openNcrs === 0
    };
}

/**
 * Get quality statistics for all suppliers
 * الحصول على إحصائيات الجودة لجميع الموردين
 */
export function getAllSuppliersQualityStats(
    suppliers: { id: string; name: string }[],
    materials: MaterialReceiving[],
    labTests: LabTest[],
    ncrs: NcrRecord[]
): SupplierQualityStats[] {
    return suppliers.map(supplier =>
        calculateSupplierQualityStats(
            supplier.id,
            supplier.name,
            materials,
            labTests,
            ncrs
        )
    );
}

// ============ NCR Analytics by Source ============

/**
 * Get NCRs related to a specific supplier
 */
export function getNcrsBySupplierId(ncrs: NcrRecord[], supplierId: string): NcrRecord[] {
    return ncrs.filter(n => n.relatedSupplierId === supplierId);
}

/**
 * Get NCRs related to a specific lab test
 */
export function getNcrsByLabTestId(ncrs: NcrRecord[], labTestId: string): NcrRecord[] {
    return ncrs.filter(n => n.relatedLabTestId === labTestId);
}

/**
 * Get NCRs related to a specific material receiving
 */
export function getNcrsByMaterialId(ncrs: NcrRecord[], materialId: string): NcrRecord[] {
    return ncrs.filter(n => n.relatedMaterialReceivingId === materialId);
}

// ============ Dashboard Stats ============

export interface IntegratedDashboardStats {
    // NCR Stats
    totalNcrs: number;
    openNcrs: number;
    autoGeneratedNcrs: number;

    // Lab Stats
    pendingLabTests: number;
    completedToday: number;
    rejectedToday: number;

    // Material Stats
    pendingMaterials: number;
    rejectedMaterials: number;

    // Supplier Stats
    suppliersWithIssues: number;
    lowScoreSuppliers: number;
}

/**
 * Calculate integrated dashboard statistics
 */
export function calculateIntegratedStats(
    ncrs: NcrRecord[],
    labTests: LabTest[],
    materials: MaterialReceiving[],
    suppliers: { id: string; qualityScore: number }[]
): IntegratedDashboardStats {
    const today = new Date().toISOString().split('T')[0];

    return {
        // NCR Stats
        totalNcrs: ncrs.length,
        openNcrs: ncrs.filter(n => n.status !== 'closed').length,
        autoGeneratedNcrs: ncrs.filter(n => n.autoGeneratedFromLab).length,

        // Lab Stats
        pendingLabTests: labTests.filter(t => t.status === 'pending' || t.status === 'in_progress').length,
        completedToday: labTests.filter(t => t.completedAt?.startsWith(today)).length,
        rejectedToday: labTests.filter(t =>
            t.status === 'rejected' && t.approvedAt?.startsWith(today)
        ).length,

        // Material Stats
        pendingMaterials: materials.filter(m => m.status === 'pending' || m.status === 'inspecting').length,
        rejectedMaterials: materials.filter(m => m.status === 'rejected').length,

        // Supplier Stats
        suppliersWithIssues: suppliers.filter(s => s.qualityScore < 70).length,
        lowScoreSuppliers: suppliers.filter(s => s.qualityScore < 50).length
    };
}
