// ==================== Permission Types & Hierarchy ====================
// Enterprise-Grade RBAC Permission Definitions

import type { Permission, PermissionHierarchy } from '../../types/rbac';

// ==================== Extended Permission Actions ====================
export const PERMISSION_ACTIONS: Permission[] = [
  {
    id: 'perm_view',
    code: 'view',
    name: 'View',
    name_ar: 'عرض',
    description: 'View and read data',
    description_ar: 'عرض وقراءة البيانات',
    action: 'view',
    display_order: 1,
  },
  {
    id: 'perm_create',
    code: 'create',
    name: 'Create',
    name_ar: 'إنشاء',
    description: 'Create new records',
    description_ar: 'إنشاء سجلات جديدة',
    action: 'create',
    display_order: 2,
    requires_permissions: ['view'],
  },
  {
    id: 'perm_edit',
    code: 'edit',
    name: 'Edit',
    name_ar: 'تعديل',
    description: 'Modify existing records',
    description_ar: 'تعديل السجلات الموجودة',
    action: 'edit',
    display_order: 3,
    requires_permissions: ['view'],
  },
  {
    id: 'perm_delete',
    code: 'delete',
    name: 'Delete',
    name_ar: 'حذف',
    description: 'Delete records permanently',
    description_ar: 'حذف السجلات نهائياً',
    action: 'delete',
    display_order: 4,
    requires_permissions: ['view', 'edit'],
    is_dangerous: true,
  },
  {
    id: 'perm_approve',
    code: 'approve',
    name: 'Approve',
    name_ar: 'موافقة',
    description: 'Approve submissions and changes',
    description_ar: 'الموافقة على الطلبات والتغييرات',
    action: 'approve',
    display_order: 5,
    requires_permissions: ['view'],
    is_dangerous: true,
  },
  {
    id: 'perm_export',
    code: 'export',
    name: 'Export',
    name_ar: 'تصدير',
    description: 'Export data to files',
    description_ar: 'تصدير البيانات إلى ملفات',
    action: 'export',
    display_order: 6,
    requires_permissions: ['view'],
  },
  {
    id: 'perm_print',
    code: 'print',
    name: 'Print',
    name_ar: 'طباعة',
    description: 'Print documents and reports',
    description_ar: 'طباعة الوثائق والتقارير',
    action: 'print',
    display_order: 7,
    requires_permissions: ['view'],
  },
  {
    id: 'perm_archive',
    code: 'archive',
    name: 'Archive',
    name_ar: 'أرشفة',
    description: 'Archive records',
    description_ar: 'أرشفة السجلات',
    action: 'archive',
    display_order: 8,
    requires_permissions: ['view', 'edit'],
  },
  {
    id: 'perm_sign',
    code: 'sign',
    name: 'Sign',
    name_ar: 'توقيع',
    description: 'Electronic signature authority',
    description_ar: 'صلاحية التوقيع الإلكتروني',
    action: 'sign',
    display_order: 9,
    requires_permissions: ['view'],
    is_dangerous: true,
  },
  {
    id: 'perm_release',
    code: 'release',
    name: 'Release',
    name_ar: 'إفراج',
    description: 'Final release authority',
    description_ar: 'صلاحية الإفراج النهائي',
    action: 'release',
    display_order: 10,
    requires_permissions: ['view', 'approve'],
    is_dangerous: true,
  },
  {
    id: 'perm_reassign',
    code: 'reassign',
    name: 'Reassign',
    name_ar: 'إعادة تعيين',
    description: 'Reassign tasks/workflows to others',
    description_ar: 'إعادة تعيين المهام للآخرين',
    action: 'reassign',
    display_order: 11,
    requires_permissions: ['view'],
  },
  {
    id: 'perm_configure',
    code: 'configure',
    name: 'Configure',
    name_ar: 'تكوين',
    description: 'Modify system settings/workflows',
    description_ar: 'تعديل إعدادات النظام',
    action: 'configure',
    display_order: 12,
    requires_permissions: ['view', 'edit'],
    is_dangerous: true,
  },
];

// ==================== Permission Hierarchy ====================
export const PERMISSION_HIERARCHY: PermissionHierarchy[] = [
  { permission_code: 'view', requires_permissions: [] },
  { permission_code: 'create', requires_permissions: ['view'] },
  { permission_code: 'edit', requires_permissions: ['view'] },
  { permission_code: 'delete', requires_permissions: ['view', 'edit'] },
  { permission_code: 'archive', requires_permissions: ['view', 'edit'] },
  { permission_code: 'approve', requires_permissions: ['view'] },
  { permission_code: 'export', requires_permissions: ['view'] },
  { permission_code: 'print', requires_permissions: ['view'] },
  { permission_code: 'sign', requires_permissions: ['view'] },
  { permission_code: 'release', requires_permissions: ['view', 'approve'] },
  { permission_code: 'reassign', requires_permissions: ['view'] },
  { permission_code: 'configure', requires_permissions: ['view', 'edit'] },
];

// ==================== Dangerous Permission Combinations ====================
export const DANGEROUS_PERMISSION_COMBINATIONS = [
  {
    module: 'audit_logs',
    action: 'delete',
    warning: 'Deleting audit logs violates compliance requirements (21 CFR Part 11, ISO 9001)',
    risk: 'critical',
    requires_justification: true,
  },
  {
    module: 'roles',
    action: 'edit',
    warning: 'Editing roles requires elevated privileges and audit justification',
    risk: 'high',
    requires_justification: true,
  },
  {
    module: 'users',
    action: 'delete',
    warning: 'Deleting users may affect audit trails and historical records',
    risk: 'high',
    requires_justification: true,
  },
  {
    module: 'batch_records',
    action: 'delete',
    warning: 'Deleting batch records may violate GMP requirements',
    risk: 'critical',
    requires_justification: true,
  },
  {
    module: 'lab_tests',
    action: 'delete',
    warning: 'Deleting lab test results may violate data integrity requirements',
    risk: 'critical',
    requires_justification: true,
  },
  {
    module: 'electronic_signatures',
    action: 'configure',
    warning: 'Modifying e-signature configuration affects regulatory compliance',
    risk: 'high',
    requires_justification: true,
  },
];

// ==================== Permission Type Categories ====================
export const PERMISSION_CATEGORIES = {
  basic: ['view', 'create', 'edit', 'delete'],
  workflow: ['approve', 'sign', 'release', 'reassign'],
  data: ['export', 'print', 'archive'],
  admin: ['configure'],
} as const;

export type PermissionCategory = keyof typeof PERMISSION_CATEGORIES;

