import { useMemo } from 'react';
import {
  BeakerIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon,
  TruckIcon,
  UserGroupIcon,
  ExclamationTriangleIcon,
  ArrowTrendingUpIcon,
} from '@heroicons/react/24/outline';
import { useLabStore } from '../../../store/labStore';
import { useMasterDataStore } from '../../../store/masterDataStore';
import { useNcrs } from '../../../hooks/ncr/useNcrs';
import { useLabV2Runs } from '../../../modules/lab_v2/hooks/useTestRuns';
import { calcTrend, countByMonth } from '../dashboard.types';
import type { KpiMetric } from '../dashboard.types';
import type { NcrRecord } from '../../../types/ncr';

export interface LabDashboardData {
  kpis: KpiMetric[];
  v2Kpis: KpiMetric[];
  recentTests: { id: string; number: string; source: string; status: string }[];
  supplierStats: { label: string; value: number; color: string }[];
  recentV2Runs: { id: string; number: string; result: string | null; status: string; createdAt: string }[];
  isLoading: boolean;
}

export function useLabDashboard(): LabDashboardData {
  const { labTests, materials, getPendingLabTests, getPendingMaterials } = useLabStore();
  const { suppliers, getApprovedSuppliers } = useMasterDataStore();
  const { ncrs } = useNcrs();
  const { data: v2Runs = [], isLoading: v2Loading } = useLabV2Runs({ limit: 200 });

  return useMemo(() => {
    // ---- Legacy lab stats ----
    const pendingTests = getPendingLabTests().length;
    const completedTests = labTests.filter(t => t.status === 'completed' || t.status === 'approved').length;
    const rejectedTests = labTests.filter(t => t.status === 'rejected').length;
    const totalTests = labTests.length;

    const pendingMaterials = getPendingMaterials().length;
    const rejectedMaterials = materials.filter(m => m.status === 'rejected').length;
    const totalMaterials = materials.length;

    const totalSuppliers = suppliers.length;
    const approvedSuppliers = getApprovedSuppliers().length;
    const supplierApprovalRate = totalSuppliers > 0 ? Math.round((approvedSuppliers / totalSuppliers) * 100) : 0;

    const materialRejectionRate = totalMaterials > 0 ? Math.round((rejectedMaterials / totalMaterials) * 100) : 0;

    const autoNcrs = ncrs.filter((n: NcrRecord) => n.autoGeneratedFromLab).length;
    const { current: curAutoNcrs } = countByMonth(
      ncrs.filter((n: NcrRecord) => n.autoGeneratedFromLab),
      (n: NcrRecord) => n.date
    );

    // ---- Lab v2 stats ----
    const v2Total = v2Runs.length;
    const v2Pass = v2Runs.filter(r => r.evaluation_result === 'pass').length;
    const v2Fail = v2Runs.filter(r => r.evaluation_result === 'fail').length;
    const v2Pending = v2Runs.filter(r => r.status === 'draft' || r.status === 'in_progress').length;
    const v2PassRate = v2Total > 0 ? Math.round((v2Pass / v2Total) * 100) : 0;

    const { current: curV2, previous: prevV2 } = countByMonth(v2Runs, r => r.created_at);
    const v2Trend = { ...calcTrend(curV2, prevV2), isPositive: true };

    const { current: curV2Pass, previous: prevV2Pass } = countByMonth(
      v2Runs.filter(r => r.evaluation_result === 'pass'), r => r.created_at
    );
    const v2PassTrend = { ...calcTrend(curV2Pass, prevV2Pass), isPositive: true };

    // ---- KPIs (legacy) ----
    const kpis: KpiMetric[] = [
      {
        id: 'pending_materials',
        label: 'مواد بانتظار الفحص',
        value: pendingMaterials,
        icon: TruckIcon,
        color: pendingMaterials > 5 ? 'orange' : 'yellow',
        highlight: pendingMaterials > 5,
        href: '/lab/receiving',
      },
      {
        id: 'material_rejection_rate',
        label: 'معدل رفض المواد',
        value: materialRejectionRate,
        unit: '%',
        icon: XCircleIcon,
        color: materialRejectionRate > 20 ? 'red' : materialRejectionRate > 10 ? 'yellow' : 'green',
        highlight: materialRejectionRate > 20,
        subtitle: `${rejectedMaterials} من ${totalMaterials} مادة`,
      },
      {
        id: 'supplier_approval_rate',
        label: 'اعتماد الموردين',
        value: supplierApprovalRate,
        unit: '%',
        icon: UserGroupIcon,
        color: supplierApprovalRate >= 80 ? 'green' : supplierApprovalRate >= 50 ? 'yellow' : 'red',
        subtitle: `${approvedSuppliers} من ${totalSuppliers}`,
        href: '/lab/suppliers',
      },
      {
        id: 'auto_ncrs',
        label: 'NCR تلقائي',
        value: autoNcrs,
        icon: ExclamationTriangleIcon,
        color: autoNcrs > 0 ? 'red' : 'green',
        highlight: autoNcrs > 3,
        subtitle: `هذا الشهر: ${curAutoNcrs}`,
        href: '/ncr',
      },
    ];

    // ---- KPIs (lab v2) ----
    const v2Kpis: KpiMetric[] = [
      {
        id: 'v2_pass_rate',
        label: 'نسبة النجاح (فحوصات v2)',
        value: v2PassRate,
        unit: '%',
        icon: CheckCircleIcon,
        color: v2PassRate >= 80 ? 'green' : v2PassRate >= 60 ? 'yellow' : 'red',
        trend: v2PassTrend,
        highlight: v2PassRate < 60 && v2Total > 0,
        subtitle: `${v2Pass} ناجح من ${v2Total}`,
        href: '/lab/tests/runs',
      },
      {
        id: 'v2_fail',
        label: 'فحوصات فاشلة',
        value: v2Fail,
        icon: XCircleIcon,
        color: v2Fail > 5 ? 'red' : v2Fail > 0 ? 'orange' : 'green',
        highlight: v2Fail > 5,
        href: '/lab/tests/runs',
      },
      {
        id: 'v2_pending',
        label: 'فحوصات معلقة',
        value: v2Pending,
        icon: ClockIcon,
        color: 'yellow',
        href: '/lab/tests/runs',
      },
      {
        id: 'v2_this_month',
        label: 'فحوصات هذا الشهر',
        value: curV2,
        icon: BeakerIcon,
        color: 'blue',
        trend: v2Trend,
        href: '/lab/tests/runs',
      },
      {
        id: 'legacy_pending',
        label: 'فحوصات قديمة معلقة',
        value: pendingTests,
        icon: ArrowTrendingUpIcon,
        color: pendingTests > 0 ? 'yellow' : 'gray',
        subtitle: `${completedTests} مكتمل`,
        href: '/lab',
      },
    ];

    // Recent legacy tests
    const recentTests = labTests
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 5)
      .map(t => ({ id: t.id, number: t.testNumber, source: t.sample?.sourceName || '', status: t.status }));

    // Recent v2 runs
    const recentV2Runs = [...v2Runs]
      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
      .slice(0, 5)
      .map(r => ({
        id: r.id,
        number: r.run_number,
        result: r.evaluation_result ?? null,
        status: r.status,
        createdAt: r.created_at,
      }));

    // Supplier stats rows
    const supplierStats = [
      { label: 'إجمالي الموردين', value: totalSuppliers, color: 'text-slate-700 dark:text-slate-300' },
      { label: 'معتمدون', value: approvedSuppliers, color: 'text-emerald-600' },
      { label: 'إجمالي المواد المستلمة', value: totalMaterials, color: 'text-blue-600' },
      { label: 'مواد مرفوضة', value: rejectedMaterials, color: 'text-red-600' },
    ];

    return {
      kpis,
      v2Kpis,
      recentTests,
      supplierStats,
      recentV2Runs,
      isLoading: v2Loading,
    };
  }, [labTests, materials, suppliers, ncrs, v2Runs, v2Loading,
      getPendingLabTests, getPendingMaterials, getApprovedSuppliers]);
}
